version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    env_file: ./.env
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/ordersApp
    ports:
      - "27017:27017"
